version: '3'
services:
  krakend:
    image: devopsfaith/krakend
    ports:
      - "8000:8000"
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
    command: run -c /etc/krakend/krakend.json
    environment:
      - FC_ENABLE=1
      - FC_OUT=/tmp/krakend.json