Server:
  Port: 8900
  ReadTimeout: 60s
  WriteTimeout: 60s

API:
  BasePath: ""
  APITimeout: 60s
  EnableSwagger: true

Database:
  SlaveDSN: "postgres://postgres:1235813@localhost:5433/ums?sslmode=disable"
  MasterDSN: "postgres://postgres:1235813@localhost:5433/ums?sslmode=disable"
  RetryInterval: 10
  MaxIdleConn: 10
  MaxConn: 10
  ConnMaxLifetime: 10s

Kafka:
  Producer:
    Brokers:
      - kafka:9092
    MaxAttempt: 5
    Idempotent: true
  Topics:
    MasterDataUser:
      Value: "ums.masterdata-users"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataKPUBranch:
      Value: "ums.masterdata-kpu-branch"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataVoter:
      Value: "ums.masterdata-voters"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataKpuKota:
      Value: "ums.masterdata-kpu-kota"
      ErrorHandler: "Phase1"
      WithBackOff: true
    MasterDataKpuProvinsi:
      Value: "ums.masterdata-kpu-provinsi"
      ErrorHandler: "Phase1"
      WithBackOff: true

JWT:
  Secret: "^87adb2&91hnGaWd7"

GrpcServer:
  Port: 35000

Encryption:
  Key : "NZkrqmVGg6Bi4QbqGXbH9wz3Q0+NCGvMKA2j8hqD5eM="

BlockchainConfig:
  GanacheURL: "http://host.docker.internal:7545"
  VotechainAddress: "0xBCc42cB1bdc6b66f19Afa3Ee82825bEDb3E66E43"
  ElectionManagerAddress: "0xFfEdBbC0E0F2b5eDCd0C13120E35cf61105cc6c6"
  KPUManagerAddress: "0x28eE5De48d3fE3c7DeA51613EEb0B499FCa26400"
  VoterManagerAddress: "0x65744d5f7655A3f0c4Fe744534DA019f0FAaf34B"
  VotechainBaseAddress: "0x7F4B0522E9dF910891d970c6030CfF402e6d6C1a"


Cors:
  AllowOrigins: "*"
  AllowMethods: "GET,POST,PUT,DELETE,OPTIONS"
  AllowHeaders: "Content-Type,Authorization"
  AllowCredentials: false
  ExposeHeaders: "X-Custom-Header"
  MaxAge: 3600